export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const AUTH_ERROR = 'AUTH_ERROR'; //if the token does not match
export const USER_LOADED = 'USER_LOADED'; 
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAIL ='LOGIN_FAIL';
export const LOGOUT ='LOGOUT';
export const GET_JOBS ='GET_JOBS';
export const GET_JOB ='GET_JOB';
export const JOB_ERROR ='JOB_ERROR';
export const UPDATE_LIKES ='UPDATE_LIKES';
export const GET_ERRORS = 'GET_ERRORS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
